version: "3.3"
services:
  php:
    build: ./bin/php
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html/
    networks:
      - default
  postgres:
    image: postgres:9.6.24-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
  adminer:
    image: adminer:4.8.1
    ports:
      - 8083:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
